### ISSUE TITLE
Doesn't work well in JRuby

### ISSUE THREAD

**Issue by eins78** [asterite/rufo#10] opened 2017-06-23 12:13 UTC
code that triggered it (minimal repro)

```ruby
def some_sql_query
  <<-SQL
    SELECT 1
  SQL
end
```

stacktrace

```
Rufo::Bug: unexpected node:     SELECT 1
 at [[3, 0], :on_tstring_content, "    SELECT 1\n"] at [[3, 0], :on_tstring_content, "    SELECT 1\n"]
                       bug at /Users/ma/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/rufo-0.0.3/lib/rufo/formatter.rb:2276
…
```

**Comment by asterite** [comment] 2017-06-23 14:17
@eins78 Thanks for the bug report, but that exact code doesn't trigger the error for me. What version of Ruby are you using?

**Comment by meineerde** [comment] 2017-06-23 17:40
I can reproduce it with JRuby 9.1.8.0 (installed with RVM) and rufo 0.0.5. On Ruby 2.4.1, this example works fine.

**Comment by asterite** [comment] 2017-06-23 19:02
Sorry, I don't think I'll try to be compatible with JRuby. I just tried it and Ripper gives incorrect results. I'm not willing to workaround those bugs and differences (though if someone else wants to fix this, PRs are welcome). There's also the thing that `jruby` takes **a lot** to boot, which is a bit impractical given that `rufo` is meant to be used as an editor plugin for fast auto-formatting.

**Comment by asterite** [comment] 2017-06-26 01:24
I'm closing this as Ripper seems to be very buggy in JRuby. For example:

```
  19) Rufo formats "foo\n  .bar # x\n  .baz" (line: 305)
      Failure/Error: Unable to find org.jruby.ext.ripper.RipperLexer.dispatchDelayedToken(RipperLexer.java to read failed line
      Java::JavaLang::NullPointerException:
      # org.jruby.ext.ripper.RipperLexer.dispatchDelayedToken(RipperLexer.java:767)
      # org.jruby.ext.ripper.RipperLexer.yylex(RipperLexer.java:1077)
      # org.jruby.ext.ripper.RipperLexer.nextToken(RipperLexer.java:360)
      # org.jruby.ext.ripper.RipperParser.yyparse(RipperParser.java:1519)
      # org.jruby.ext.ripper.RipperParser.yyparse(RipperParser.java:1470)
      # org.jruby.ext.ripper.RipperParserBase.parse(RipperParserBase.java:78)
      # org.jruby.ext.ripper.RubyRipper.parse(RubyRipper.java:327)
      ....
```

**Closed by asterite** 2017-06-26 01:24 UTC
Labels: JRuby

**Comment by eins78** [comment] 2017-06-26 08:09
I can confirm that I was running it under JRuby, and that it was merely by accident (yes it is to slow to start to run a formatter).

@asterite Maybe it would make sense to not support JRuby at all (bail out with appropriate error message) if it is this buggy.

```
$ time ruby -v
jruby 9.1.5.0 (2.3.1) 2016-09-07 036ce39 Java HotSpot(TM) 64-Bit Server VM 25.112-b16 on 1.8.0_112-b16 +jit [darwin-x86_64]

real    0m0.591s
```
